---
- name: Triage Down Interfaces 
  hosts: "{{ rtr }}"
  gather_facts: False
  tasks:
  - name: Attempt a No shut for {{ inventory_hostname }} {{ interface }}
    ansible.netcommon.network_resource:
      os_name: "{{ ansible_network_os }}"
      name: interfaces
      config: 
      - name: "{{ interface }}"
        enabled: True
      state: merged
    
  - name: Check Interface State for {{ inventory_hostname }} {{ interface }}
    ansible.netcommon.cli_command:
      command: show ip interface {{ interface }}
    register: int_state

  - name: Print Event Info
    ansible.builtin.debug:
      var: int_state.stdout_lines

  - name: Assert that {{ inventory_hostname }} {{ interface }} is UP
    ansible.builtin.assert:
     that: 
        - "'line protocol is up' in int_state['stdout']"
     fail_msg: "{{ inventory_hostname }} {{ interface }} line protocol is down"
     success_msg: "{{ inventory_hostname }} {{ interface }} line protocol is up"
    register: check

  - debug:
      msg: "{{ check }}"
    when: evaluated_to is false



