---
- name: Triage Down Interfaces 
  hosts: "{{ rtr }}"
  gather_facts: False
  tasks:
  - name: Attempt a No shut for {{ inventory_hostname }} {{ interface }}
    ansible.netcommon.network_resource:
      os_name: "{{ ansible_network_os }}"
      name: interfaces
      config: 
      - name: "{{ interface }}"
        enabled: True
      state: merged
    
  - name: Check Interface State for {{ inventory_hostname }} {{ interface }}
    ansible.netcommon.cli_command:
      command: show ip interface brief
    register: int_state

  - name: Print Event Info
    ansible.builtin.debug:
      var: int_state.stdout_lines
