---
- name: Triage Down Interfaces 
  hosts: "{{ rtr }}"
  gather_facts: False
  tasks:
  - name: Attempt a No shut for {{ inventory_hostname }} {{ interface }}
    ansible.netcommon.network_resource:
      os_name: "{{ ansible_network_os }}"
      name: interfaces
      config: 
      - name: "{{ interface }}"
        enabled: True
      state: merged
    
  - name: Check Interface State for {{ inventory_hostname }} {{ interface }}
    ansible.netcommon.cli_command:
      command: show ip interface brief {{ interface }}
    register: int_state

  - name: Print Event Info
    ansible.builtin.debug:
      var: int_state.stdout_lines

  - name: Assert that {{ inventory_hostname }} {{ interface }} is UP
    ansible.builtin.assert:
     that: 
        - "'FULL/' in ospf['stdout'][0]"
     fail_msg: "OSPF neighbor is not present"
     success_msg: "OSPF Neighbor is Full"
    retries: 3
    delay: 10

